import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "SteadFast Studios",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <Navbar />
                <main className="container m-0 mx-auto max-w-[95dvw] rounded-4xl bg-zinc-100 px-6 py-8 md:px-12 lg:py-16 xl:max-w-7xl xl:py-20">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
