import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: {
        template: "%s | SteadFast Studio",
        default: "SteadFast Studio", // a default is required when creating a template
    },
    description: "Generated by create next app",
    generator: "Next.js",
    applicationName: "Next.js",
    referrer: "origin-when-cross-origin",
    keywords: ["Next.js", "React", "JavaScript"],
    authors: [
        { name: "Sanchari Mandal", url: "https://github.com/sanchari" },
        { name: "Kankan Mondal", url: "https://github.com/sanchari" },
    ],
    creator: "Sanchari Mandal",
    publisher: "GitHub",
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    openGraph: {
        title: "SteadFast Studio",
        description: "Your partner in digital excellence.",
        url: "https://steadfast-studio.vercel.app/",
        siteName: "SteadFast Studio",
        images: [
            {
                url: "https://steadfast-studio.vercel.app/og-image.png",
                width: 1200,
                height: 630,
                alt: "SteadFast Studio OG Image",
            },
        ],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: "SteadFast Studio",
        description: "Your partner in digital excellence.",
        images: ["https://steadfast-studio.vercel.app/og-image.png"],
        creator: "@sanchari_mandal",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} bg-white antialiased`}>
                <Navbar />
                <main className="m-0 mx-auto w-full py-6">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
